version: '3.5'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    networks:
      - engine-net
      - bos-net
      - cos-net
      - qos-net
    ports:
      - '80:80'
    expose:
      - '80'
    container_name: ms-nginx
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: the
      MYSQL_DATABASE: heavenms
    networks:
      - engine-net
      - bos-net
      - cos-net
      - qos-net
    ports:
      - '3306:3306'
    expose:
      - '3306'
    container_name: ms-db
  bos:
    image: ms-bos:latest
    depends_on:
      - "db"
      - "engine"
      - "nginx"
      - "logs"
    ports:
      - '8581:5005'
    environment:
      WAIT_HOSTS: db:3306, nginx:80
    networks:
      - bos-net
    expose:
      - '8080'
    volumes:
      - ./config.yaml:/config.yaml:ro
    container_name: ms-bos
  cos:
    image: ms-cos:latest
    depends_on:
      - "db"
      - "engine"
      - "nginx"
      - "logs"
    ports:
      - '8582:5005'
    environment:
      WAIT_HOSTS: db:3306, nginx:80
    networks:
      - cos-net
    expose:
      - '8080'
    volumes:
      - ./config.yaml:/config.yaml:ro
    container_name: ms-cos
  logs:
    image: ms-logs:latest
    ports:
      - '8583:5005'
    networks:
      - engine-net
      - bos-net
      - cos-net
      - qos-net
    expose:
      - '8080'
    container_name: ms-logs
  qos:
    image: ms-qos:latest
    depends_on:
      - "db"
      - "engine"
      - "nginx"
      - "logs"
    ports:
      - '8584:5005'
    environment:
      WAIT_HOSTS: db:3306, nginx:80
    networks:
      - qos-net
    expose:
      - '8080'
    volumes:
      - ./config.yaml:/qos/config.yaml:ro
    container_name: ms-qos
  engine:
    user: root
    build:
      context: .
      dockerfile: engine.Dockerfile
    depends_on:
      - "db"
      - "logs"
    ports:
      - '8484:8484'
      - '7575:7575'
      - '7576:7576'
      - '7577:7577'
      - '8580:5005'
    expose:
      - '8080'
      - '8484'
      - '7575'
      - '7576'
      - '7577'
    environment:
      WAIT_HOSTS: db:3306
    networks:
      - engine-net
    volumes:
      - ./wz:/wz:ro
      - ./script:/script:ro
      - ./config.yaml:/config.yaml:ro
    container_name: ms-engine
networks:
  bos-net:
    name: bos-net
    driver: bridge
  cos-net:
    name: cos-net
    driver: bridge
  qos-net:
    name: qos-net
    driver: bridge
  engine-net:
    name: engine-net
    driver: bridge