package net.server.channel.packet;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import net.server.MaplePacket;
import net.server.PacketReader;
import net.server.channel.packet.reader.AcceptFamilyReader;
import net.server.channel.packet.reader.AcceptToSReader;
import net.server.channel.packet.reader.AdminChatReader;
import net.server.channel.packet.reader.AdminCommandReader;
import net.server.channel.packet.reader.AfterLoginReader;
import net.server.channel.packet.reader.AllianceRegisterOperationReader;
import net.server.channel.packet.reader.AssignAPReader;
import net.server.channel.packet.reader.AutoAggroReader;
import net.server.channel.packet.reader.BBSOperationReader;
import net.server.channel.packet.reader.BeholderReader;
import net.server.channel.packet.reader.BuddyReader;
import net.server.channel.packet.reader.CancelBuffReader;
import net.server.channel.packet.reader.CancelChairReader;
import net.server.channel.packet.reader.CancelItemEffectReader;
import net.server.channel.packet.reader.CashOperationReader;
import net.server.channel.packet.reader.ChangeChannelReader;
import net.server.channel.packet.reader.ChangeMapReader;
import net.server.channel.packet.reader.ChangeMapSpecialReader;
import net.server.channel.packet.reader.CharacterInfoRequestReader;
import net.server.channel.packet.reader.CharacterListRequestReader;
import net.server.channel.packet.reader.CharacterSelectedReader;
import net.server.channel.packet.reader.CharacterSelectedWithPicReader;
import net.server.channel.packet.reader.CheckCharacterNameReader;
import net.server.channel.packet.reader.CoconutReader;
import net.server.channel.packet.reader.CouponCodeReader;
import net.server.channel.packet.reader.CreateCharacterReader;
import net.server.channel.packet.reader.DamageReader;
import net.server.channel.packet.reader.DamageSummonReader;
import net.server.channel.packet.reader.DeleteCharacterReader;
import net.server.channel.packet.reader.DenyAllianceRequestReader;
import net.server.channel.packet.reader.DenyGuildRequestReader;
import net.server.channel.packet.reader.DenyPartyRequestReader;
import net.server.channel.packet.reader.DistributeAPReader;
import net.server.channel.packet.reader.DistributeSPReader;
import net.server.channel.packet.reader.DoorReader;
import net.server.channel.packet.reader.DueyReader;
import net.server.channel.packet.reader.ExistingAllianceOperationReader;
import net.server.channel.packet.reader.FaceExpressionReader;
import net.server.channel.packet.reader.FamilyPreceptsReader;
import net.server.channel.packet.reader.FamilySummonResponseReader;
import net.server.channel.packet.reader.FamilyUseReader;
import net.server.channel.packet.reader.FieldDamageMobReader;
import net.server.channel.packet.reader.FrederickReader;
import net.server.channel.packet.reader.GeneralChatReader;
import net.server.channel.packet.reader.GiveFameReader;
import net.server.channel.packet.reader.GrenadeEffectReader;
import net.server.channel.packet.reader.GuildOperationReader;
import net.server.channel.packet.reader.HealOvertimeReader;
import net.server.channel.packet.reader.InventoryMergeReader;
import net.server.channel.packet.reader.InventorySortReader;
import net.server.channel.packet.reader.ItemMoveReader;
import net.server.channel.packet.reader.ItemPickupReader;
import net.server.channel.packet.reader.KeymapChangeReader;
import net.server.channel.packet.reader.LoginPasswordReader;
import net.server.channel.packet.reader.MTSReader;
import net.server.channel.packet.reader.MakerActionReader;
import net.server.channel.packet.reader.MesoDropReader;
import net.server.channel.packet.reader.MessengerReader;
import net.server.channel.packet.reader.MobBanishPlayerReader;
import net.server.channel.packet.reader.MobDamageMobFriendlyReader;
import net.server.channel.packet.reader.MobDamageMobReader;
import net.server.channel.packet.reader.MonsterBombReader;
import net.server.channel.packet.reader.MonsterBookCoverReader;
import net.server.channel.packet.reader.MonsterCarnivalReader;
import net.server.channel.packet.reader.MoveDragonReader;
import net.server.channel.packet.reader.MoveLifeReader;
import net.server.channel.packet.reader.MovePlayerReader;
import net.server.channel.packet.reader.MoveSummonReader;
import net.server.channel.packet.reader.MultiChatReader;
import net.server.channel.packet.reader.NPCAnimationReader;
import net.server.channel.packet.reader.NPCMoreTalkReader;
import net.server.channel.packet.reader.NPCShopReader;
import net.server.channel.packet.reader.NPCTalkReader;
import net.server.channel.packet.reader.NewYearCardReader;
import net.server.channel.packet.reader.NoteActionReader;
import net.server.channel.packet.reader.OpenFamilyPedigreeReader;
import net.server.channel.packet.reader.OwlWarpReader;
import net.server.channel.packet.reader.PartyOperationReader;
import net.server.channel.packet.reader.PartySearchStartReader;
import net.server.channel.packet.reader.PetAutoPotReader;
import net.server.channel.packet.reader.PetChatReader;
import net.server.channel.packet.reader.PetCommandReader;
import net.server.channel.packet.reader.PetExcludeItemsReader;
import net.server.channel.packet.reader.PetFoodReader;
import net.server.channel.packet.reader.PetLootReader;
import net.server.channel.packet.reader.PetMovementReader;
import net.server.channel.packet.reader.PlayerInteractionReader;
import net.server.channel.packet.reader.PlayerLoggedInReader;
import net.server.channel.packet.reader.QuestActionReader;
import net.server.channel.packet.reader.RPSActionReader;
import net.server.channel.packet.reader.RaiseUIStateReader;
import net.server.channel.packet.reader.ReactorHitReader;
import net.server.channel.packet.reader.RegisterPicReader;
import net.server.channel.packet.reader.RegisterPinReader;
import net.server.channel.packet.reader.RemoteGachaponReader;
import net.server.channel.packet.reader.ReportReader;
import net.server.channel.packet.reader.RingActionReader;
import net.server.channel.packet.reader.ScriptedItemReader;
import net.server.channel.packet.reader.ScrollReader;
import net.server.channel.packet.reader.ServerStatusRequestReader;
import net.server.channel.packet.reader.SetGenderReader;
import net.server.channel.packet.reader.SkillBookReader;
import net.server.channel.packet.reader.SkillEffectReader;
import net.server.channel.packet.reader.SkillMacroReader;
import net.server.channel.packet.reader.SnowballReader;
import net.server.channel.packet.reader.SpawnPetReader;
import net.server.channel.packet.reader.SpecialMoveReader;
import net.server.channel.packet.reader.SpouseChatReader;
import net.server.channel.packet.reader.StorageReader;
import net.server.channel.packet.reader.SummonDamageReader;
import net.server.channel.packet.reader.TakeDamageReader;
import net.server.channel.packet.reader.TeleportRockMapReader;
import net.server.channel.packet.reader.TouchReactorReader;
import net.server.channel.packet.reader.TransferNameReader;
import net.server.channel.packet.reader.TransferNameResultReader;
import net.server.channel.packet.reader.TransferWorldReader;
import net.server.channel.packet.reader.UseCashItemReader;
import net.server.channel.packet.reader.UseCatchItemReader;
import net.server.channel.packet.reader.UseChairReader;
import net.server.channel.packet.reader.UseDeathItemReader;
import net.server.channel.packet.reader.UseItemEffectReader;
import net.server.channel.packet.reader.UseItemReader;
import net.server.channel.packet.reader.UseItemUIReader;
import net.server.channel.packet.reader.UseMapleLifeReader;
import net.server.channel.packet.reader.UseMountFoodReader;
import net.server.channel.packet.reader.UseSolomonReader;
import net.server.channel.packet.reader.ViewAllCharactersRegisterPicReader;
import net.server.channel.packet.reader.ViewAllCharactersSelectedReader;
import net.server.channel.packet.reader.ViewAllCharactersSelectedWithPicReader;
import net.server.channel.packet.reader.WeddingReader;
import net.server.channel.packet.reader.WeddingTalkReader;
import net.server.channel.packet.reader.WhisperReader;
import net.server.packet.reader.CustomReader;
import net.server.packet.reader.NoOpReader;
import tools.data.input.SeekableLittleEndianAccessor;

public class PacketReaderFactory {
   private static PacketReaderFactory ourInstance = new PacketReaderFactory();

   private static Map<Class<? extends PacketReader>, PacketReader> readers;

   public static PacketReaderFactory getInstance() {
      return ourInstance;
   }

   private PacketReaderFactory() {
      readers = new HashMap<>();
      readers.put(NoOpReader.class, new NoOpReader());
      readers.put(CustomReader.class, new CustomReader());

      readers.put(AcceptToSReader.class, new AcceptToSReader());
      readers.put(AfterLoginReader.class, new AfterLoginReader());
      readers.put(CharacterListRequestReader.class, new CharacterListRequestReader());
      readers.put(CharacterSelectedReader.class, new CharacterSelectedReader());
      readers.put(LoginPasswordReader.class, new LoginPasswordReader());
      readers.put(CreateCharacterReader.class, new CreateCharacterReader());
      readers.put(DeleteCharacterReader.class, new DeleteCharacterReader());
      readers.put(ViewAllCharactersSelectedReader.class, new ViewAllCharactersSelectedReader());
      readers.put(RegisterPinReader.class, new RegisterPinReader());
      readers.put(RegisterPicReader.class, new RegisterPicReader());
      readers.put(CharacterSelectedWithPicReader.class, new CharacterSelectedWithPicReader());
      readers.put(SetGenderReader.class, new SetGenderReader());
      readers.put(ViewAllCharactersSelectedWithPicReader.class, new ViewAllCharactersSelectedWithPicReader());
      readers.put(ViewAllCharactersRegisterPicReader.class, new ViewAllCharactersRegisterPicReader());
      readers.put(ServerStatusRequestReader.class, new ServerStatusRequestReader());

      readers.put(TransferNameReader.class, new TransferNameReader());
      readers.put(TransferNameResultReader.class, new TransferNameResultReader());
      readers.put(TransferWorldReader.class, new TransferNameReader());
      readers.put(ChangeChannelReader.class, new ChangeChannelReader());
      readers.put(GeneralChatReader.class, new GeneralChatReader());
      readers.put(WhisperReader.class, new WhisperReader());
      readers.put(NPCTalkReader.class, new NPCTalkReader());
      readers.put(NPCMoreTalkReader.class, new NPCMoreTalkReader());
      readers.put(QuestActionReader.class, new QuestActionReader());
      readers.put(GrenadeEffectReader.class, new GrenadeEffectReader());
      readers.put(NPCShopReader.class, new NPCShopReader());
      readers.put(InventoryMergeReader.class, new InventoryMergeReader());
      readers.put(ItemMoveReader.class, new ItemMoveReader());
      readers.put(MesoDropReader.class, new MesoDropReader());
      readers.put(PlayerLoggedInReader.class, new PlayerLoggedInReader());
      readers.put(ChangeMapReader.class, new ChangeMapReader());
      readers.put(CheckCharacterNameReader.class, new CheckCharacterNameReader());
      readers.put(UseCashItemReader.class, new UseCashItemReader());
      readers.put(UseItemReader.class, new UseItemReader());
      readers.put(ScrollReader.class, new ScrollReader());
      readers.put(FaceExpressionReader.class, new FaceExpressionReader());
      readers.put(HealOvertimeReader.class, new HealOvertimeReader());
      readers.put(ItemPickupReader.class, new ItemPickupReader());
      readers.put(CharacterInfoRequestReader.class, new CharacterInfoRequestReader());
      readers.put(CancelBuffReader.class, new CancelBuffReader());
      readers.put(CancelItemEffectReader.class, new CancelItemEffectReader());
      readers.put(PlayerInteractionReader.class, new PlayerInteractionReader());
      readers.put(RPSActionReader.class, new RPSActionReader());
      readers.put(DistributeAPReader.class, new DistributeAPReader());
      readers.put(DistributeSPReader.class, new DistributeSPReader());
      readers.put(KeymapChangeReader.class, new KeymapChangeReader());
      readers.put(ChangeMapSpecialReader.class, new ChangeMapSpecialReader());
      readers.put(StorageReader.class, new StorageReader());
      readers.put(GiveFameReader.class, new GiveFameReader());
      readers.put(PartyOperationReader.class, new PartyOperationReader());
      readers.put(DenyPartyRequestReader.class, new DenyPartyRequestReader());
      readers.put(MultiChatReader.class, new MultiChatReader());
      readers.put(DoorReader.class, new DoorReader());
      readers.put(DamageSummonReader.class, new DamageSummonReader());
      readers.put(BuddyReader.class, new BuddyReader());
      readers.put(UseItemEffectReader.class, new UseItemEffectReader());
      readers.put(UseChairReader.class, new UseChairReader());
      readers.put(CancelChairReader.class, new CancelChairReader());
      readers.put(ReactorHitReader.class, new ReactorHitReader());
      readers.put(GuildOperationReader.class, new GuildOperationReader());
      readers.put(DenyGuildRequestReader.class, new DenyGuildRequestReader());
      readers.put(BBSOperationReader.class, new BBSOperationReader());
      readers.put(SkillEffectReader.class, new SkillEffectReader());
      readers.put(MessengerReader.class, new MessengerReader());
      readers.put(SpawnPetReader.class, new SpawnPetReader());
      readers.put(NPCAnimationReader.class, new NPCAnimationReader());
      readers.put(CashOperationReader.class, new CashOperationReader());
      readers.put(CouponCodeReader.class, new CouponCodeReader());
      readers.put(PetChatReader.class, new PetChatReader());
      readers.put(PetCommandReader.class, new PetCommandReader());
      readers.put(PetFoodReader.class, new PetFoodReader());
      readers.put(PetLootReader.class, new PetLootReader());
      readers.put(AutoAggroReader.class, new AutoAggroReader());
      readers.put(MonsterBombReader.class, new MonsterBombReader());
      readers.put(SkillBookReader.class, new SkillBookReader());
      readers.put(SkillMacroReader.class, new SkillMacroReader());
      readers.put(NoteActionReader.class, new NoteActionReader());
      readers.put(UseMountFoodReader.class, new UseMountFoodReader());
      readers.put(MTSReader.class, new MTSReader());
      readers.put(RingActionReader.class, new RingActionReader());
      readers.put(SpouseChatReader.class, new SpouseChatReader());
      readers.put(PetAutoPotReader.class, new PetAutoPotReader());
      readers.put(PetExcludeItemsReader.class, new PetExcludeItemsReader());
      readers.put(OwlWarpReader.class, new OwlWarpReader());
      readers.put(TeleportRockMapReader.class, new TeleportRockMapReader());
      readers.put(MobBanishPlayerReader.class, new MobBanishPlayerReader());
      readers.put(MobDamageMobReader.class, new MobDamageMobReader());
      readers.put(ReportReader.class, new ReportReader());
      readers.put(MonsterBookCoverReader.class, new MonsterBookCoverReader());
      readers.put(OpenFamilyPedigreeReader.class, new OpenFamilyPedigreeReader());
      readers.put(FamilyPreceptsReader.class, new FamilyPreceptsReader());
      readers.put(FamilySummonResponseReader.class, new FamilySummonResponseReader());
      readers.put(ScriptedItemReader.class, new ScriptedItemReader());
      readers.put(TouchReactorReader.class, new TouchReactorReader());
      readers.put(BeholderReader.class, new BeholderReader());
      readers.put(DenyAllianceRequestReader.class, new DenyAllianceRequestReader());
      readers.put(UseSolomonReader.class, new UseSolomonReader());
      readers.put(NewYearCardReader.class, new NewYearCardReader());
      readers.put(RemoteGachaponReader.class, new RemoteGachaponReader());
      readers.put(AcceptFamilyReader.class, new AcceptFamilyReader());
      readers.put(DueyReader.class, new DueyReader());
      readers.put(UseDeathItemReader.class, new UseDeathItemReader());
      readers.put(UseMapleLifeReader.class, new UseMapleLifeReader());
      readers.put(UseCatchItemReader.class, new UseCatchItemReader());
      readers.put(FieldDamageMobReader.class, new FieldDamageMobReader());
      readers.put(MobDamageMobFriendlyReader.class, new MobDamageMobFriendlyReader());
      readers.put(PartySearchStartReader.class, new PartySearchStartReader());
      readers.put(SnowballReader.class, new SnowballReader());
      readers.put(CoconutReader.class, new CoconutReader());
      readers.put(FrederickReader.class, new FrederickReader());
      readers.put(WeddingReader.class, new WeddingReader());
      readers.put(WeddingTalkReader.class, new WeddingTalkReader());
      readers.put(RaiseUIStateReader.class, new RaiseUIStateReader());
      readers.put(UseItemUIReader.class, new UseItemUIReader());
      readers.put(DamageReader.class, new DamageReader());
      readers.put(SummonDamageReader.class, new SummonDamageReader());
      readers.put(FamilyUseReader.class, new FamilyUseReader());
      readers.put(InventorySortReader.class, new InventorySortReader());
      readers.put(MonsterCarnivalReader.class, new MonsterCarnivalReader());
      readers.put(TakeDamageReader.class, new TakeDamageReader());
      readers.put(AssignAPReader.class, new AssignAPReader());
      readers.put(AdminChatReader.class, new AdminChatReader());
      readers.put(PetMovementReader.class, new PetMovementReader());
      readers.put(ExistingAllianceOperationReader.class, new ExistingAllianceOperationReader());
      readers.put(AllianceRegisterOperationReader.class, new AllianceRegisterOperationReader());
      readers.put(MakerActionReader.class, new MakerActionReader());
      readers.put(AdminCommandReader.class, new AdminCommandReader());
      readers.put(MoveLifeReader.class, new MoveLifeReader());
      readers.put(MovePlayerReader.class, new MovePlayerReader());
      readers.put(MoveSummonReader.class, new MoveSummonReader());
      readers.put(MoveDragonReader.class, new MoveDragonReader());
      readers.put(SpecialMoveReader.class, new SpecialMoveReader());
   }

   public <T extends MaplePacket> PacketReader<T> get(Class<? extends PacketReader<T>> readerClass) {
      return (PacketReader<T>) readers.get(readerClass);
   }

   public <T extends MaplePacket> Optional<T> read(Class<? extends PacketReader<T>> readerClass, SeekableLittleEndianAccessor accessor) {
      if (readers.containsKey(readerClass)) {
         PacketReader<T> reader = get(readerClass);
         return Optional.of(reader.read(accessor));
      } else {
         return Optional.empty();
      }
   }
}
